import { BRAND } from '../../core/brand'
/**
 * Email templates.
 *
 * Plain functions returning html + text. No template engine: the set is small
 * and a dependency here would add a build step for six emails.
 *
 * Every template ships a text alternative. HTML-only mail scores badly with
 * spam filters, and an invoice landing in spam is direct revenue loss for the
 * user — which makes deliverability a product concern, not a detail.
 */

export interface RenderedEmail {
  html: string
  text: string
}

const ACCENT = BRAND.colors.accent
const INK = BRAND.colors.ink

function shell(body: string, preheader: string): string {
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>TaxPedestal</title></head>
<body style="margin:0;padding:0;background:#F6F7F9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
<span style="display:none;font-size:0;line-height:0;max-height:0;overflow:hidden;">${preheader}</span>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F6F7F9;padding:32px 16px;">
<tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#ffffff;border-radius:14px;border:1px solid #E4E7EC;">
<tr><td style="padding:28px 32px 0;">
<span style="font-size:19px;font-weight:700;letter-spacing:-0.02em;color:${INK};">${BRAND.name}</span>
</td></tr>
<tr><td style="padding:20px 32px 32px;color:${INK};font-size:15px;line-height:1.6;">
${body}
</td></tr>
</table>
<p style="max-width:560px;margin:20px auto 0;color:#667085;font-size:12px;line-height:1.5;text-align:left;">
Sent by ${BRAND.name}. If you weren't expecting this email you can safely ignore it.
</p>
</td></tr></table>
</body></html>`
}

function button(url: string, label: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:24px 0;">
<tr><td style="background:${ACCENT};border-radius:8px;">
<a href="${url}" style="display:inline-block;padding:12px 22px;color:#ffffff;font-size:15px;font-weight:600;text-decoration:none;">${label}</a>
</td></tr></table>`
}

export type TemplateName =
  | 'verify-email'
  | 'reset-password'
  | 'invoice-sent'
  | 'invoice-reminder'
  | 'payment-received'
  | 'team-invitation'

type Data = Record<string, unknown>

/** Minimal HTML escaping for interpolated user content. */
function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function render(template: TemplateName, data: Data): RenderedEmail {
  const d = (key: string, fallback = ''): string => esc(data[key] ?? fallback)
  // URLs are generated by us, never user-supplied, so they are not escaped
  // (escaping would corrupt query separators).
  const url = (key: string): string => String(data[key] ?? '')

  switch (template) {
    case 'verify-email':
      return {
        html: shell(
          `<p>Hi ${d('fullName')},</p>
<p>Confirm your email address to finish setting up your TaxPedestal workspace.</p>
${button(url('url'), 'Confirm email address')}
<p style="color:#667085;font-size:13px;">Or paste this into your browser:<br>${url('url')}</p>`,
          'Confirm your email address',
        ),
        text: `Hi ${data.fullName},\n\nConfirm your email address to finish setting up your TaxPedestal workspace:\n${url('url')}\n`,
      }

    case 'reset-password':
      return {
        html: shell(
          `<p>Hi ${d('fullName')},</p>
<p>Use the link below to choose a new password. It expires in ${d('expiresInMinutes', '60')} minutes.</p>
${button(url('url'), 'Choose a new password')}
<p style="color:#667085;font-size:13px;">If you didn't request this, no action is needed — your password hasn't changed.</p>`,
          'Reset your password',
        ),
        text: `Hi ${data.fullName},\n\nChoose a new password (expires in ${data.expiresInMinutes ?? 60} minutes):\n${url('url')}\n\nIf you didn't request this, no action is needed.\n`,
      }

    case 'invoice-sent':
      return {
        html: shell(
          `<p>Hi ${d('clientName')},</p>
<p>${d('orgName')} has sent you invoice <strong>${d('invoiceNumber')}</strong> for <strong>${d('amount')}</strong>, due ${d('dueDate')}.</p>
${button(url('url'), 'View and pay invoice')}
${data.notes ? `<p style="padding:14px 16px;background:#F6F7F9;border-radius:8px;color:#475467;font-size:14px;">${d('notes')}</p>` : ''}`,
          `Invoice ${d('invoiceNumber')} from ${d('orgName')} — ${d('amount')}`,
        ),
        text: `Hi ${data.clientName},\n\n${data.orgName} has sent you invoice ${data.invoiceNumber} for ${data.amount}, due ${data.dueDate}.\n\nView and pay: ${url('url')}\n`,
      }

    case 'invoice-reminder':
      return {
        html: shell(
          `<p>Hi ${d('clientName')},</p>
<p>A reminder that invoice <strong>${d('invoiceNumber')}</strong> for <strong>${d('amount')}</strong> ${d('statusLine')}.</p>
${button(url('url'), 'View and pay invoice')}
<p style="color:#667085;font-size:13px;">Already paid? Reply to this email and ${d('orgName')} will check.</p>`,
          `Reminder: invoice ${d('invoiceNumber')} — ${d('amount')}`,
        ),
        text: `Hi ${data.clientName},\n\nA reminder that invoice ${data.invoiceNumber} for ${data.amount} ${data.statusLine}.\n\nView and pay: ${url('url')}\n`,
      }

    case 'payment-received':
      return {
        html: shell(
          `<p>Hi ${d('recipientName')},</p>
<p><strong>${d('amount')}</strong> was received for invoice <strong>${d('invoiceNumber')}</strong>${data.clientName ? ` from ${d('clientName')}` : ''}.</p>
<p style="color:#0E9F6E;font-weight:600;">${d('statusLine')}</p>
${button(url('url'), 'View invoice')}`,
          `Payment received — ${d('amount')}`,
        ),
        text: `Hi ${data.recipientName},\n\n${data.amount} was received for invoice ${data.invoiceNumber}.\n${data.statusLine}\n\n${url('url')}\n`,
      }

    case 'team-invitation':
      return {
        html: shell(
          `<p>Hi,</p>
<p>${d('inviterName')} has invited you to join <strong>${d('orgName')}</strong> on TaxPedestal as ${d('role')}.</p>
${button(url('url'), 'Accept invitation')}
<p style="color:#667085;font-size:13px;">This invitation expires in ${d('expiresInDays', '7')} days.</p>`,
          `${d('inviterName')} invited you to ${d('orgName')}`,
        ),
        text: `${data.inviterName} has invited you to join ${data.orgName} on TaxPedestal as ${data.role}.\n\nAccept: ${url('url')}\n`,
      }

    default: {
      // Exhaustiveness guard: adding a TemplateName without a case fails to compile.
      const never: never = template
      throw new Error(`Unhandled email template: ${String(never)}`)
    }
  }
}
